### ISSUE TITLE
Make endpoints relative

### ISSUE THREAD

**Issue by Pandry** [aiforensics/tkobservatory#1]
Hello
Endpoints are statically tied to the `trex.zone` endpoint  

https://github.com/aiforensics/tkobservatory/blob/501f3dafb64bf50e250fe1bd52799af8b9c9d1ba/src/constants/index.js#L5-L9

Is it possible to put it this way:

```js
export const GLOBAL_RECOMMENDATIONS_API =
  "/foryourecommendations/global";
export const TOP_COUNRTY_API =
  "/foryourecommendations/topByCountry";
export const SEARCH_API = "/foryourecommendations";
```

Or make it configurable by an env variable or file?

**Comment by rekoke** [comment]
this is solved in this commit: https://github.com/aiforensics/tkobservatory/commit/baa94efe1fb2a241abf87768bf348644b7ab334a
